console.log("==========QUESTION:01==============");
var pinCode=413314;
var myName="Vidyarani";
var isMarried=true;
console.log("pincode:",pinCode,"Type:",typeof pinCode);
console.log("Name:",myName,"Type:",typeof myName);
console.log("Married Status:",isMarried,"Type:", typeof isMarried);
console.log("=============================================");
console.log("=================QUESTION:02============================");
var Null="It Is the intentional absence of the values. It is one of the primitive values of JavaScript.";
var Undefined="It means the value does not exist in the complier.";
console.log("Null:",Null);
console.log("Undefined",Undefined);
